# -*- coding: utf-8 -*-
"""Simple_Content-Based_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NB36veFAnfQkeXvi6WU1EKBWn1LivWw7

##**AI/Machine Learning Intern Challenge: Simple Content-Based Recommendation**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
import re
pd.set_option('display.max_columns' , None)
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
df = pd.read_csv('/content/netflix_data.csv')

# Display the first few rows
df.head()

df.info()

df.sample(25)

df1 = df[['title', 'description']].dropna()

df1.head()

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = vectorizer.fit_transform(df["description"])

from sklearn.metrics.pairwise import cosine_similarity

def recommend_movies(query, top_n=5):
    query_vec = vectorizer.transform([query])
    similarity = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarity.argsort()[-top_n:][::-1]
    return df.iloc[top_indices][['title', 'description']]

# Example Query
user_query = "I love thrilling action movies set in space, with a comedic twist."
recommendations = recommend_movies(user_query)
print(recommendations)

user_query = "I like action movies set in space"
recommendations = recommend_movies(user_query)
print(recommendations)

recommendations.head()

